version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - iplocation-net
    restart: always


  api-service:
    image: jisjo/ipgeolocation-api-service:v1
    container_name: iplocation-api
    networks:
      - iplocation-net
    restart: always
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - APP_PORT=8080
      - API_KEY_FROM_SECRETSMANAGER=True
      - SECRET_NAME= api_key_ipgeolocation
      - SECRET_KEY=api_key
      - REGION_NAME=us-east-2

  frontend-service:
    image: jisjo/ipgeolocation-frontend:v1
    container_name: ipgeolocation-frontend
    networks:
      - iplocation-net
    restart: always
    ports:
      - "80:8080"
    environment:
      - API_SERVER=iplocation-api
      - API_SERVER_PORT=8080
      - API_PATH=/api/v1/
      - APP_PORT=8080

networks:
  iplocation-net:
